name=LoggerInterface
version=1.0.0
author=Szymon Bandel
maintainer=Szymon Bandel
sentence=A lightweight logger interface with Serial backend.
paragraph=This library provides a basic logging interface and a SerialLogger implementation for ESP32/Arduino.
category=Communication
url=https://github.com/DonSimonio/LoggerInterface
architectures=*
